### ISSUE TITLE
Alerts Config Status: RetryCount is not set to 0 after resolving the errors 

### ISSUE THREAD

**Issue by phanipadala** [keikoproj/alert-manager#28]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug
**What happened**:
We had an invalid alert value in the spec which resulted in an error state in the AlertsConfig status. After correcting the value , RetryCount has not reset to 0.

**What you expected to happen**:
RetryCount should reset to 0 .

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- alert-manager version
- Kubernetes version :
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:

```
- controller logs:
```
$ kubectl logs <alert-manager>
```

**Comment by lilwan** [comment]
retryCount under alertsConfig status is the total retry count for all the alerts, it is incorrect to reset it for only one alert correction. we probably can add logic to reset the retryCount when all the associated alerts are in Ready state @mnkg561

**Comment by mnkg561** [comment]
Yeah. You are correct. See, If you can change that in this block  https://github.com/keikoproj/alert-manager/blob/28d280b4ef5bb186b7a9e3b3afc686572b6d2ef5/controllers/alertsconfig_controller.go#L212-L249 since it loops for all the individual alert configs and will be taken care for every request at the end.
